# MixOmics PLS-DA
# E. Lamont
# 2/23/26

# I think this becomes a predictive model maybe??

# https://mixomics.org/methods/spls-da/
# https://mixomicsteam.github.io/mixOmics-Vignette/id_02.html#id_02
# https://mixomics.org/case-studies/splsda-srbct-case-study-2/

# if (!requireNamespace("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# BiocManager::install("mixOmics")
library(mixOmics)

# I guess I can use log2(TPM+1) or do the EdgeR CPM...

source("Import_data.R")


###########################################################
####################### PROCESS DATA ######################

myX <- GoodSamples60_tpmf %>% # Using TPM to start...
  dplyr::select(-contains("THP1")) %>%
  dplyr::select(-contains("Broth")) %>% # Lets take out broth as well
  t()

# Remove genes (columns) that are all zero
myX <- myX[, colSums(myX) != 0] # Remove columns that are all zero so the scale works for prcomp

# Want this to be Type2 I guess 
my_pipeSummary2 <- my_pipeSummary %>%
  slice(match(rownames(myX), SampleID2)) # Match the rows then just keep the one that are the same
stopifnot(all(rownames(myX) %in% my_pipeSummary2$SampleID2))
myY <- my_pipeSummary2 %>%
  pull(Type2) %>%
  factor()

summary(myY)
# W0 sputum (cure) W0 sputum (relapse)    W2 sputum (cure) W2 sputum (relapse) 
# 32                  11                   8                   5 


###########################################################
################# PCA PRELIMINARY ANALYSIS ################
# As in most cases when developing models, exploring the data to determine the major sources of variation is a good first step. PCA will be used for this. As described in the PCA Methods Page, centering and scaling is recommended to homogenize the variance across the genes. ncomp is set to an arbitrarily high number to understand the captured variance across cotheremponents.

# run pca method on data
pca.1 = pca(myX, ncomp = 10, center = TRUE, scale = TRUE) 
plot(pca.1)  # barplot of the eigenvalues (explained variance per component)

# Two components would be sufficient to explain a moderate proportion of the data’s variance according to Figure 1. Next, the data is projected onto these two components to attempt to observe sources of variation.
plotIndiv(pca.1, group = my_pipeSummary2$Type2, ind.names = FALSE, # plot the samples projected
          legend = TRUE, title = 'MixOmics PCA') # onto the PCA subspace


###########################################################
################## INITIAL sPLS-DA MODEL ##################

my.splsda <- splsda(myX, myY, ncomp = 10)  # set ncomp to 10 for performance assessment later

# A PLS-DA model is fitted with ten components to evaluate the performance and the number of components necessary for the final model. 
# The background.predict() function can also be utilised to depict the separation of class labels. This plot provides intuition on how novel samples would be classified according to the model generated by sPLS-DA.

# plot the samples projected onto the first two components of the PLS-DA subspace
plotIndiv(my.splsda , comp = 1:2, 
          group = my_pipeSummary2$Type2, ind.names = FALSE,  # colour points by class
          ellipse = TRUE, # include 95% confidence ellipse for each class
          legend = TRUE, title = 'PLSDA with confidence ellipses')

# use the max.dist measure to form decision boundaries between classes based on PLS-DA data
background = background.predict(my.splsda, comp.predicted=2, dist = "max.dist")

# plot the samples projected onto the first two components of the PLS-DA subspace
plotIndiv(my.splsda, comp = 1:2,
          group = my_pipeSummary2$Type2, ind.names = FALSE, # colour points by class
          background = background, # include prediction background for each class
          legend = TRUE, title = "PLSDA with prediction background")










