# MixOmics sparse PLS-DA W0 samples only
# Not keeping out a validation set
# E. Lamont
# 5/15/26

###****************###
# RESULTS:
# The AUC is 0.9261 for Component 1 and 1 for Componenet 1,2.....
# Component 1 genes used: Rv0625c, Rv2331A
###****************###

# https://mixomics.org/case-studies/splsda-srbct-case-study-2/
# https://mixomics.org/methods/spls-da/

source("Import_data.R")

# if (!requireNamespace("BiocManager", quietly = TRUE))
#   install.packages("BiocManager")
# BiocManager::install("mixOmics")
library(mixOmics)

###########################################################
######################### SET PATHS #######################

my_nfolds <- 4
my_nrepeats <- 30

my_folderPath <- "Figures/PredictiveModeling/AllTrain/MixOmics_W0_TPM"
my_figureTitle <- "MixOmics sPLSDA TPM"



###########################################################
##################### ORGANIZE DATA #######################

tpm_t <- GoodSamples60_tpmf %>% 
  t() %>%
  as.data.frame() %>%
  rownames_to_column("SampleID2")

model_df <- GoodSamples60_pipeSummary %>% 
  filter(Type == "Week 0 sputum") %>%
  dplyr::select(SampleID2, Outcome) %>%
  mutate(Outcome = factor(Outcome, levels = c("Cure", "Relapse"))) %>% # Really don't know what order it should be....
  inner_join(tpm_t, by = "SampleID2") %>%
  column_to_rownames("SampleID2") %>%
  na.omit()

myX <- model_df %>% dplyr::select(-Outcome)
myY <- model_df$Outcome

# Remove genes (columns) that are all zero
myX <- myX[, colSums(myX) != 0] # Remove columns that are all zero so the scale works for prcomp
# Now 4025, just a less fancy way of doing the nzv



###########################################################
################# PCA PRELIMINARY ANALYSIS ################
# As in most cases when developing models, exploring the data to determine the major sources of variation is a good first step. PCA will be used for this. As described in the PCA Methods Page, centering and scaling is recommended to homogenize the variance across the genes. ncomp is set to an arbitrarily high number to understand the captured variance across cotheremponents.

# run pca method on data
pca.1 = pca(myX, ncomp = 10, center = TRUE, scale = TRUE) 
plot(pca.1)  # barplot of the eigenvalues (explained variance per component)
# Saved with Export

# Two components would be sufficient to explain a moderate proportion of the data’s variance according to Figure 1. Next, the data is projected onto these two components to attempt to observe sources of variation.
PCA1 <- plotIndiv(pca.1, group = myY, ind.names = T, # plot the samples projected 
                  legend = TRUE, title = 'MixOmics PCA', 
                  col = c("#0072B2", "#bc5300"),)
PCA1$graph



###########################################################
################## INITIAL sPLS-DA MODEL ##################

# Initial model
set.seed(23)
train.splsda <- mixOmics::splsda(myX, myY, ncomp = 10) # set ncomp to 10 for performance assessment later

# A PLS-DA model is fitted with ten components to evaluate the performance and the number of components necessary for the final model. 
# The background.predict() function can also be utilised to depict the separation of class labels. This plot provides intuition on how novel samples would be classified according to the model generated by sPLS-DA.

# plot the samples projected onto the first two components of the PLS-DA subspace
train_PLSDA_1 <- plotIndiv(train.splsda , comp = 1:2, 
                           group = myY, ind.names = F,  # colour points by class
                           ellipse = TRUE, # include 95% confidence ellipse for each class
                           legend = TRUE, 
                           col = c("#0072B2", "#bc5300"),
                           title = 'W0 sPLSDA with confidence ellipses')
train_PLSDA_1$graph

# use the max.dist measure to form decision boundaries between classes based on PLS-DA data
set.seed(23)
background = background.predict(train.splsda, comp.predicted=2, dist = "max.dist")
# plot the samples projected onto the first two components of the PLS-DA subspace
train_PLSDA_2 <- plotIndiv(train.splsda, comp = 1:2,
                           group = myY, ind.names = FALSE, # colour points by class
                           background = background, # include prediction background for each class
                           col = c("#0072B2", "#bc5300"),
                           legend = TRUE, title = "W0 sPLSDA with prediction background")
# ggsave(train_PLSDA_2$graph,
#        file = paste0("sPLSDA2_TrainSet.pdf"),
#        path = my_folderPath,
#        width = 8, height = 5, units = "in")

###########################################################
####################### TUNE sPLS-DA ######################

## SELECTING THE NUMBER OF COMPONENTS ##
# The ncomp Parameter

# The number of components to use is a crucial decision and is dictated by the performance of the PLS-DA model - i.e. its ability to correctly classify novel samples. The perf() function is used for this exactly. This is done with repeated cross-validation. Based on the output of this function, the optimal number of components to use can be identified.
# 
# A three-fold, 10 repeat cross-validation procedure is utilised here. Generally, for datasets with numerous samples, at least 10 folds is recommended. 3 or 5 folds is appropriate for smaller datasets and those with minimal samples should use Leave-One-Out (LOO) validation. Consider using 50-100 repeats to reduce the impact of the randomly allocated folds during each repeat.
# 
# The overall error rate (OER) and balanced error rate (BER) for the three different distance metrics (explained further below) across the first ten components are depicted in Figure 4.

# undergo performance evaluation in order to tune the number of components to use
set.seed(23)
perf.splsda.train <- perf(train.splsda, validation = "Mfold", 
                          folds = my_nfolds, nrepeat = my_nrepeats, 
                          progressBar = T, auc = TRUE) # include AUC values

# plot the outcome of performance evaluation across all ten components
plot(perf.splsda.train, col = color.mixo(5:7), sd = TRUE,
     legend.position = "vertical")

# what is the optimal value of components according to perf()
perf.splsda.train$choice.ncomp 
# max.dist centroids.dist mahalanobis.dist
# overall        1              1                1
# BER            1              1                1

## SELECTING THE NUMBER OF VARIABLES ##
# The keepX Parameter

# In order to determine the number of variables used to construct each latent component, the tune.splsda() function is utilised. This is performed iteratively, such that components are tuned one at a time. Through this function, the classification error rate can be extracted and averaged across folds and repeats. As mentioned above, an appropriate number of repeats would be around 50-100.
# 
# Up to four components were selected as per Figure 4. In this case, five-fold cross validation was repeated ten times using the BER of max.dist as the performance measure - where minimisation was optimal. The cpus parameter allows for the use of parallelisation of computation as tuning can take a long time on low-to-mid range processors.
# 
# The output of the tuning is shown in Figure 5. The diamond indicates the optimal number of variables to keep for a given component, selected by which keepX value achieves the lowest classification error rate as determined with a one-sided t−test. The error bars indicate the standard deviation across the repeated, cross-validated folds.

# grid of possible keepX values that will be tested for each component
list.keepX <- c(1:10,  seq(20, 300, 10))

# undergo the tuning process to determine the optimal number of variables
set.seed(23)
tune.splsda.train <- tune.splsda(myX, myY, ncomp = 4, # calculate for first 2 components
                                 validation = 'Mfold',
                                 folds = my_nfolds, nrepeat = my_nrepeats,
                                 dist = 'max.dist', # use max.dist measure
                                 measure = "BER", # use balanced error rate of dist measure
                                 test.keepX = list.keepX)

plot(tune.splsda.train, col = color.jet(4)) # plot output of variable number tuning
# Each colored line is a BER. SD is based on repeated cross validation folds.
# As sPLS-DA is an iterative algorithm, values represented for a given component (e.g. comp 1 to 2) include the optimal keepX value chosen for the previous component (comp 1).

tune.splsda.train$choice.ncomp$ncomp # what is the optimal value of components according to tune.splsda
# [1] 1

# what are the optimal values of variables according to tune.splsda()
tune.splsda.train$choice.keepX 
# comp1 comp2 comp3 comp4 
# 1   300   240    50 

# Doesn't work when It's 1, has to at least be two
optimal.ncomp <- 2
optimal.keepX <- tune.splsda.train$choice.keepX[1:optimal.ncomp.train]

###########################################################
####################### FINAL MODEL #######################

# Using all the tuned parameters from above, the final sPLS-DA model can be formed.

# form final model with optimised values for component and variable count
final.splsda <- splsda(myX, myY, 
                       ncomp = optimal.ncomp, 
                       keepX = optimal.keepX)


###########################################################
####################### FINAL PLOTS #######################

Tuned_PLSDA_1 <- plotIndiv(final.splsda , comp = c(1,2),
                                      group = myY, ind.names = F, 
                                      ellipse = TRUE, # include 95% confidence ellipse
                                      legend = TRUE,
                                      col = c("#0072B2", "#bc5300"),
                                      title = 'W0 Final sPLSDA comp 1&2')
# ggsave(sPLSDA_FinalModel_Comp12$graph,
#        file = paste0("sPLSDA_TrainSet_FinalModel.pdf"),
#        path = my_folderPath,
#        width = 8, height = 5, units = "in")

# use the max.dist measure to form decision boundaries between classes based on PLS-DA data
background = background.predict(final.splsda, comp.predicted=2, dist = "max.dist")
# plot the samples projected onto the first two components of the PLS-DA subspace
sPLSDA_FinalModel_Comp12_v2 <- plotIndiv(final.splsda , comp = c(1,2),
                                         group = myY, ind.names = F, 
                                         background = background,
                                         legend = TRUE,
                                         col = c("#0072B2", "#bc5300"),
                                         title = 'W0 Final sPLSDA comp 1&2')
# ggsave(sPLSDA_FinalModel_Comp12_v2$graph,
#        file = paste0("sPLSDA2_TrainSet_FinalModel.pdf"),
#        path = my_folderPath,
#        width = 8, height = 5, units = "in")


###############################################################
################ VARIABLE PLOTS FROM FINAL sPLSDA #############
# The stability of a given feature is defined as the proportion of cross validation folds (across repeats) where it was selected for to be used for a given component. Those with the highest stability are likely to be much more “important” for a given component.
# View(perf.splsda.train$features$stable) # Extract stability values
# hmmm everything is 1....

# form new perf() object which utilises the final model
set.seed(23)
perf.final.splsda <- perf(
  final.splsda,
  folds = my_nfolds, 
  nrepeat = my_nrepeats, # use repeated cross-validation
  validation = "Mfold", dist = "max.dist",  # use max.dist measure
  progressBar = FALSE)

# plot the stability of each feature for the first three components, 'h' type refers to histogram
# par(mfrow=c(1,3))
plot(perf.final.splsda$features$stable[[1]], type = 'h', 
     ylab = 'Stability', 
     xlab = 'Features', 
     main = '(a) Comp 1', las =2)
plot(perf.final.splsda$features$stable[[2]], type = 'h', 
     ylab = 'Stability', 
     xlab = 'Features', 
     main = '(b) Comp 2', las =2)
plot(perf.final.splsda$features$stable[[3]], type = 'h', 
     ylab = 'Stability', 
     xlab = 'Features',
     main = '(c) Comp 3', las =2)
# Saved with Export

# Save the variable features table
my_list <- perf.final.splsda$features$stable
my_list_df <- lapply(my_list, function(x) {
  data.frame(Feature = x)
})
# write_xlsx(my_list_df, paste0(my_folderPath, "/Variable_Stability_Final.xlsx"))

## Correlation Circle Plot ##
plotVar(final.splsda, comp = c(1,2), cex = 3) # generate correlation circle plot

###########################################################
############################ ROC ##########################
auc.splsda = auroc(final.splsda, roc.comp = 1, print = FALSE) # AUROC for the first component
auc.splsda = auroc(final.splsda, roc.comp = 2, print = F) # AUROC for all three components
# Saved via export

